# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI1005.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_dizhi = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_dizhi.setGeometry(QtCore.QRect(80, 25, 360, 20))
        self.lineEdit_dizhi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_dizhi.setObjectName("lineEdit_dizhi")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 25, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_banben = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_banben.setGeometry(QtCore.QRect(80, 60, 90, 20))
        self.lineEdit_banben.setObjectName("lineEdit_banben")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButto_ysmm = QtWidgets.QPushButton(self.groupBox)
        self.pushButto_ysmm.setGeometry(QtCore.QRect(312, 60, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButto_ysmm.setFont(font)
        self.pushButto_ysmm.setObjectName("pushButto_ysmm")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 471, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_size = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_size.setGeometry(QtCore.QRect(80, 70, 71, 20))
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(160, 70, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_ysdizhi = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ysdizhi.setGeometry(QtCore.QRect(80, 30, 360, 20))
        self.lineEdit_ysdizhi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_ysdizhi.setObjectName("lineEdit_ysdizhi")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_ys = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_ys.setGeometry(QtCore.QRect(310, 70, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ys.setFont(font)
        self.pushButton_ys.setObjectName("pushButton_ys")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 250, 471, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_mmbanben = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_mmbanben.setGeometry(QtCore.QRect(80, 70, 90, 20))
        self.lineEdit_mmbanben.setObjectName("lineEdit_mmbanben")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_mmdizhi = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_mmdizhi.setGeometry(QtCore.QRect(80, 30, 360, 20))
        self.lineEdit_mmdizhi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_mmdizhi.setObjectName("lineEdit_mmdizhi")
        self.pushButton_mm = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_mm.setGeometry(QtCore.QRect(310, 70, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_mm.setFont(font)
        self.pushButton_mm.setObjectName("pushButton_mm")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 23))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButto_ysmm.clicked.connect(MainWindow.btn_click_ysmm)
        self.pushButton_ys.clicked.connect(MainWindow.btn_click_ys)
        self.pushButton_mm.clicked.connect(MainWindow.btn_click_mm)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SWR工具箱"))
        self.groupBox.setTitle(_translate("MainWindow", "压缩重命名"))
        self.label_3.setText(_translate("MainWindow", "视频地址："))
        self.lineEdit_banben.setText(_translate("MainWindow", "下载版"))
        self.label_5.setText(_translate("MainWindow", " 版  本："))
        self.pushButto_ysmm.setText(_translate("MainWindow", "执行"))
        self.groupBox_5.setTitle(_translate("MainWindow", "压缩"))
        self.lineEdit_size.setText(_translate("MainWindow", "30"))
        self.label_7.setText(_translate("MainWindow", "M"))
        self.label_8.setText(_translate("MainWindow", "视频地址："))
        self.label_9.setText(_translate("MainWindow", "压 缩 至："))
        self.pushButton_ys.setText(_translate("MainWindow", "执行"))
        self.groupBox_6.setTitle(_translate("MainWindow", "重命名"))
        self.lineEdit_mmbanben.setText(_translate("MainWindow", "下载版"))
        self.label_17.setText(_translate("MainWindow", "视频地址："))
        self.pushButton_mm.setText(_translate("MainWindow", "执行"))
        self.label_6.setText(_translate("MainWindow", " 版  本："))

